# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: utf8
  database: noted_development
  pool: 5
  timeout: 5000
  username: Sho
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: noted_test
  timeout: 5000
  pool: 5
  username: Sho
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: noted_production
  timeout: 5000
  pool: 5
  username:
  password:
